DROP TABLE IF EXISTS USER_INFO_MDJ;
CREATE TABLE USER_INFO_MDJ
(
    ID         VARCHAR(1000) NOT NULL,
    PW         VARCHAR(100) NOT NULL,
    NAME       VARCHAR(10),
    NICKNAME   VARCHAR(10),
    AGE        NUMBER(10),
    ADDRESS    VARCHAR(25),
    EMAIL      VARCHAR(1000),
    USE_YN     CHAR(1),
    FAIL_CNT   NUMBER(10),
    PRIMARY KEY (ID)
);